- name: Update apt cache and install prerequisites
  apt:
    update_cache: yes
    name:
      - docker.io
      - docker-compose
      - git
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  user:
    name: ubuntu  # Change this if your username is different
    groups: docker
    append: yes

- name: Verify Docker installation
  command: docker --version
  register: docker_version
  changed_when: false

- name: Show installed Docker version
  debug:
    msg: "Installed Docker version: {{ docker_version.stdout }}"